services:
  cln:
    container_name: cln 
    build: ./containers/cln
    volumes:
      - ./containers/cln/volume:/app
    ports:
      - 8080:4321
    networks:
      - cln

networks:
  cln:
    name: bitcoin 
    external: true
